### PR TITLE
Wlcom protocol

### PR DESCRIPTION
**Pull request by jav4**
Initial implementation of weatherlink.com protocol. Allows capture of WeatherLink Live history data.

No data will be uploaded to WeatherLink.com

Configuration:
- Add "wlcom = True" to config file.
- If desired, change archive interval rate in _ _init_ _.py file (currently, 1 minute). WLL health data reporting stays at 15 minutes.

In order to force WLL to connect to the driver, traffic needs to be diverted to it somehow. Multiple options available:
- Use DNAT in iptables (or similar) to send TCP port 5621 traffic to WeeWX server.
- Change DNS address response to WLL when asking for IP for wdi.weatherlink.com.

History data is deleted from WLL when sent, so special care is taken on saving it. If an unexpected WeeWX crash happens, some data may be lost. Safe WeeWX shutdown procedure would be:
1.- Create /tmp/weewx-wlcom.shut file
2.- If /tmp/weewx-wlcom.lck file is present, wait for it to disappear.
3.- Signal WeeWX to shut down.

Pending topics:
- Find a way to complete authentication locally, without wl.com connection.
- Confirm radiation & UV data format. (done!)
- Confirm Leaf & Soil data format.

### CODE REVIEW

**Comment by michael-slx** [comment]
Oh, wow! Amazing work.

I currently don't have the infrastructure to look into the network capture part. I hope to find the time to look into this over the course of the next weeks.

**Comment by michael-slx** [comment]
Ok, I just did some testing and playing with your changes. Great work figuring out the protocol.

The only issue I noticed is that the UV index values are sometimes off, but correct at other times. Solar is always correct though.

---

I also took a look at the code and I've a question:
Why do we need the lock file mechanism? If I understand correctly, it makes sure that packets are only ack'd if they have been saved. What's the shutdown file for?

**Comment by jav4** [comment]
I have a Vantage Vue that doesn't have UV or Solar sensors, so the format for those (same as for Leaf/Soil) is guessed based on frame length and order. If you can share some samples of data (packet dump will be great) plus the real values of those samples, (correct and incorrect ones), I'll fine-tune them.

If needed, I've written a Python script that dumps the packet while WeeWX is live so you don't have to mess with the driver's code.

Lock & shutdown mechanisms are just safeguards against data lost. When WLL sends an archive packet, it expects a response within 30 seconds, and when it gets it, it forgets that packet, so WeeWX has up to 30 seconds to save it before losing it. I try to delay the ack as much as I can to wait for WeeWX to save it in the database, but with a 1 minute archive interval, that's not always feasible. If WeeWX crashes or it is stopped while a packet has been already been acked but it hasn't been saved yet, it won't be retransmitted and it'll be lost.

Unfortunately, WeeWX architecture doesn't have a shutdown mechanism in which it signals the shutdown to the driver and keeps everything operational (saving included) until it's ready to stop, so lock & shutdown system allows it. Just add these lines to the stop script before signalling WeeWX to stop:

```
   # A packet may have been Ack'd but not processed from wl.com. Wait...
   LCKFILE=/tmp/weewx-wlcom.lck
    SHUTFILE=/tmp/weewx-wlcom.shut
    touch $SHUTFILE
    while true
    do
        if [ -f $LCKFILE ]
        then
            if [ $(($(date +%s) - $(ls -l --time-style=+%s $LCKFILE | cut -d" " -f6) - 0)) -gt 60 ]
            then
                rm $LCKFILE
                break
            fi
        else
            break
        fi
        sleep 2
    done
```

If you don't care about losing archive packets when shutting down/crashing, just ignore the whole locking thing. Please be aware that any archive packet not transmitted to WeeWX will be stored and sent by WLL when the system starts again.

**Comment by michael-slx** [comment]
Here's a [packet capture](https://github.com/michael-slx/WLCom-Protocol/tree/main/captures/2022-07-30) that ran for about 1 hour. Also included is the terminal output of `weewxd` (using the mainline driver version).

Additionally, there's a [description of my setup](https://github.com/michael-slx/WLCom-Protocol/blob/87316be3bebb3c063a622e3ae16df69db3d7e3c2/vantage2-setup.md) including any ids.

**Comment by jav4** [comment]
UV fields updated. Now there should be correct. There still one unknown field in the ISS archive frame. Looks like it's only 0 at the hour. Maybe marking start of something?

**Comment by jav4** [comment]
TXId isn't directly available in the loop or archive packets. LSId to TXId mapping is present in configuration packets, which are only sent by wl.com when a configuration change is done.

We could implement the configuration part on the driver, but it's quite some work. I wonder if it's worth it. I'd rather focus in making it fully offline first (without the initial authentication frame) and possibly finishing off the leaf/soil part.

**Comment by michael-slx** [comment]
TXId and LSId are available via HTTP requests, though. I was thinking we could cache LSIds from HTTP responses and build a lookup table that way.

**Comment by selectSt4r** [comment]
jav4 -- curious -- what's the main intended use of your mod?  Keeping onboard WLL records as the source-of-truth and for store-and-forward in the event weewx becomes unavailable?  At what point do you begin to purge records on the WLL, if ever -- after commits to the weewx DB are confirmed?  Again, just curious about what your user requirements are.

**Comment by jav4** [comment]
The intended use is to use WLL archive packets information instead of trying to guess it (i.e. wind gust) including health data normally not available in the local API. Also, archive data from weewx unavailability windows will be recovered, instead of having gaps as of now. Finally, I'd like it to work fully offline, but this is still WiP.
WLL deletes its records as soon as they're confirmed from weewx, and it won't send another one until the previous one is confirmed. It can store a few weeks worth of data, but as soon it's confirmed, is gone. That's why I'm putting extra care on saving them.

**Comment by gary-hammer** [comment]
So, I have control over my DNS, have a test WeeWX instance.
Is this ready for user testing?
If so, how would I go about installing the Wlcom protocol version of the driver?

**Comment by jav4** [comment]
> So, I have control over my DNS, have a test WeeWX instance. Is this ready for user testing? If so, how would I go about installing the Wlcom protocol version of the driver?

You can just download this tree and replace your current driver installation with it. A backup copy is always a wise option, tho.

Add "wlcom = True" to config file, and configure your DNS to answer with your server IP address when WLL asks for wdi.weatherlink.com. Please remember that your server still needs to know the real address of wdi.weatherlink.com.

That should be it. Restarting the server and unplugging/replugging WLL from the network once you have the DNS server set up should make it work.,

If you have leaf/soil sensors, those aren't supported yet. I need someone with one of those to capture some information to implement them.

**Pull request closed without merging**
